[2025-04-30T17:55:32.880+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: superset_sync.create_superset_dataset manual__2025-04-30T17:55:30.395410+00:00 [queued]>
[2025-04-30T17:55:32.886+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: superset_sync.create_superset_dataset manual__2025-04-30T17:55:30.395410+00:00 [queued]>
[2025-04-30T17:55:32.886+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-04-30T17:55:32.896+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): create_superset_dataset> on 2025-04-30 17:55:30.395410+00:00
[2025-04-30T17:55:32.900+0000] {standard_task_runner.py:57} INFO - Started process 2364 to run task
[2025-04-30T17:55:32.902+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'superset_sync', 'create_superset_dataset', 'manual__2025-04-30T17:55:30.395410+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/superset_sync.py', '--cfg-path', '/tmp/tmpkvpj89hg']
[2025-04-30T17:55:32.903+0000] {standard_task_runner.py:85} INFO - Job 30: Subtask create_superset_dataset
[2025-04-30T17:55:32.915+0000] {logging_mixin.py:150} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-30T17:55:32.939+0000] {task_command.py:410} INFO - Running <TaskInstance: superset_sync.create_superset_dataset manual__2025-04-30T17:55:30.395410+00:00 [running]> on host a2dde070184b
[2025-04-30T17:55:33.082+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='superset_sync' AIRFLOW_CTX_TASK_ID='create_superset_dataset' AIRFLOW_CTX_EXECUTION_DATE='2025-04-30T17:55:30.395410+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-30T17:55:30.395410+00:00'
[2025-04-30T17:55:33.361+0000] {superset_sync.py:67} INFO - Dataset уже есть (id=1)
[2025-04-30T17:55:33.361+0000] {python.py:183} INFO - Done. Returned value was: 1
[2025-04-30T17:55:33.391+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=superset_sync, task_id=create_superset_dataset, execution_date=20250430T175530, start_date=20250430T175532, end_date=20250430T175533
[2025-04-30T17:55:33.435+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-04-30T17:55:33.457+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
