[2025-05-09T22:05:46.735+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: superset_sync.create_graph_dashboard manual__2025-05-09T22:05:35.807744+00:00 [queued]>
[2025-05-09T22:05:46.742+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: superset_sync.create_graph_dashboard manual__2025-05-09T22:05:35.807744+00:00 [queued]>
[2025-05-09T22:05:46.742+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-05-09T22:05:46.750+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): create_graph_dashboard> on 2025-05-09 22:05:35.807744+00:00
[2025-05-09T22:05:46.754+0000] {standard_task_runner.py:57} INFO - Started process 24278 to run task
[2025-05-09T22:05:46.757+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'superset_sync', 'create_graph_dashboard', 'manual__2025-05-09T22:05:35.807744+00:00', '--job-id', '428', '--raw', '--subdir', 'DAGS_FOLDER/superset_sync.py', '--cfg-path', '/tmp/tmpoqv513l3']
[2025-05-09T22:05:46.757+0000] {standard_task_runner.py:85} INFO - Job 428: Subtask create_graph_dashboard
[2025-05-09T22:05:46.768+0000] {logging_mixin.py:150} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-09T22:05:46.794+0000] {task_command.py:410} INFO - Running <TaskInstance: superset_sync.create_graph_dashboard manual__2025-05-09T22:05:35.807744+00:00 [running]> on host d3632ec65b22
[2025-05-09T22:05:46.857+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='superset_sync' AIRFLOW_CTX_TASK_ID='create_graph_dashboard' AIRFLOW_CTX_EXECUTION_DATE='2025-05-09T22:05:35.807744+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-09T22:05:35.807744+00:00'
[2025-05-09T22:05:47.149+0000] {superset_sync.py:83} INFO - Dataset уже есть (id=2)
[2025-05-09T22:05:47.272+0000] {superset_sync.py:194} INFO - ✔ создан чарт 'Распределение клиентов по сообществам'
[2025-05-09T22:05:47.328+0000] {superset_sync.py:194} INFO - ✔ создан чарт 'Топ-10 влиятельных клиентов'
[2025-05-09T22:05:47.361+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-05-09T22:05:47.369+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=superset_sync, task_id=create_graph_dashboard, execution_date=20250509T220535, start_date=20250509T220546, end_date=20250509T220547
[2025-05-09T22:05:47.410+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-05-09T22:05:47.436+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
