[2025-04-23T14:55:26.994+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transform.test_spark_connection manual__2025-04-23T14:54:15.015061+00:00 [queued]>
[2025-04-23T14:55:27.001+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transform.test_spark_connection manual__2025-04-23T14:54:15.015061+00:00 [queued]>
[2025-04-23T14:55:27.001+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2025-04-23T14:55:27.013+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): test_spark_connection> on 2025-04-23 14:54:15.015061+00:00
[2025-04-23T14:55:27.018+0000] {standard_task_runner.py:57} INFO - Started process 215 to run task
[2025-04-23T14:55:27.020+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'transform', 'test_spark_connection', 'manual__2025-04-23T14:54:15.015061+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/transform.py', '--cfg-path', '/tmp/tmp1js6z7jl']
[2025-04-23T14:55:27.021+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask test_spark_connection
[2025-04-23T14:55:27.064+0000] {task_command.py:410} INFO - Running <TaskInstance: transform.test_spark_connection manual__2025-04-23T14:54:15.015061+00:00 [running]> on host 77e8e38ee964
[2025-04-23T14:55:27.226+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='finbest' AIRFLOW_CTX_DAG_ID='transform' AIRFLOW_CTX_TASK_ID='test_spark_connection' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T14:54:15.015061+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-23T14:54:15.015061+00:00'
[2025-04-23T14:55:27.227+0000] {logging_mixin.py:150} INFO - JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
[2025-04-23T14:55:27.235+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2025-04-23T14:55:27.235+0000] {logging_mixin.py:150} INFO - Spark connection host: spark://spark-master:7077
[2025-04-23T14:55:27.236+0000] {logging_mixin.py:150} INFO - Ошибка при подключении к Spark Master: [Errno -2] Name or service not known
[2025-04-23T14:55:27.236+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/transform.py", line 83, in test_spark_connection
    s.connect((spark_conn.host.replace("spark://", ""), 7077))
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/transform.py", line 89, in test_spark_connection
    raise Exception(f"Не удалось подключиться к Spark Master: {e}")
Exception: Не удалось подключиться к Spark Master: [Errno -2] Name or service not known
[2025-04-23T14:55:27.244+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=transform, task_id=test_spark_connection, execution_date=20250423T145415, start_date=20250423T145526, end_date=20250423T145527
[2025-04-23T14:55:27.253+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 10 for task test_spark_connection (Не удалось подключиться к Spark Master: [Errno -2] Name or service not known; 215)
[2025-04-23T14:55:27.272+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-04-23T14:55:27.299+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
