[2025-04-23T13:32:46.986+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transform.detect_suspicious manual__2025-04-23T13:30:35.516747+00:00 [queued]>
[2025-04-23T13:32:46.993+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transform.detect_suspicious manual__2025-04-23T13:30:35.516747+00:00 [queued]>
[2025-04-23T13:32:46.993+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2025-04-23T13:32:47.009+0000] {taskinstance.py:1327} INFO - Executing <Task(SparkSubmitOperator): detect_suspicious> on 2025-04-23 13:30:35.516747+00:00
[2025-04-23T13:32:47.015+0000] {standard_task_runner.py:57} INFO - Started process 297 to run task
[2025-04-23T13:32:47.017+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'transform', 'detect_suspicious', 'manual__2025-04-23T13:30:35.516747+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/transform.py', '--cfg-path', '/tmp/tmp9m2rcztj']
[2025-04-23T13:32:47.018+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask detect_suspicious
[2025-04-23T13:32:47.061+0000] {task_command.py:410} INFO - Running <TaskInstance: transform.detect_suspicious manual__2025-04-23T13:30:35.516747+00:00 [running]> on host 067f3e9d3d0e
[2025-04-23T13:32:47.233+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='finbest' AIRFLOW_CTX_DAG_ID='transform' AIRFLOW_CTX_TASK_ID='detect_suspicious' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T13:30:35.516747+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-23T13:30:35.516747+00:00'
[2025-04-23T13:32:47.242+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2025-04-23T13:32:47.243+0000] {spark_submit.py:339} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --executor-cores 2 --executor-memory 2g --driver-memory 1g --name arrow-spark /opt/spark/detect_suspicious.py --jdbc jdbc:postgresql://postgres:5432/finbest --clickhouse-url jdbc:clickhouse://clickhouse:8123/finbest
[2025-04-23T13:32:47.335+0000] {spark_submit.py:490} INFO - /home/airflow/.local/lib/python3.7/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-04-23T13:32:47.336+0000] {spark_submit.py:490} INFO - JAVA_HOME is not set
[2025-04-23T13:32:47.347+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --executor-cores 2 --executor-memory 2g --driver-memory 1g --name arrow-spark /opt/spark/detect_suspicious.py --jdbc jdbc:postgresql://postgres:5432/finbest --clickhouse-url jdbc:clickhouse://clickhouse:8123/finbest. Error code is: 1.
[2025-04-23T13:32:47.350+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=transform, task_id=detect_suspicious, execution_date=20250423T133035, start_date=20250423T133246, end_date=20250423T133247
[2025-04-23T13:32:47.362+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 10 for task detect_suspicious (Cannot execute: spark-submit --master spark://spark-master:7077 --executor-cores 2 --executor-memory 2g --driver-memory 1g --name arrow-spark /opt/spark/detect_suspicious.py --jdbc jdbc:postgresql://postgres:5432/finbest --clickhouse-url jdbc:clickhouse://clickhouse:8123/finbest. Error code is: 1.; 297)
[2025-04-23T13:32:47.389+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-04-23T13:32:47.413+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
