[2025-04-23T10:23:48.555+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transform.detect_suspicious manual__2025-04-23T10:21:37.571973+00:00 [queued]>
[2025-04-23T10:23:48.561+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transform.detect_suspicious manual__2025-04-23T10:21:37.571973+00:00 [queued]>
[2025-04-23T10:23:48.562+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2025-04-23T10:23:48.573+0000] {taskinstance.py:1327} INFO - Executing <Task(SparkSubmitOperator): detect_suspicious> on 2025-04-23 10:21:37.571973+00:00
[2025-04-23T10:23:48.577+0000] {standard_task_runner.py:57} INFO - Started process 866 to run task
[2025-04-23T10:23:48.579+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'transform', 'detect_suspicious', 'manual__2025-04-23T10:21:37.571973+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/transform.py', '--cfg-path', '/tmp/tmpd3cufe5i']
[2025-04-23T10:23:48.580+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask detect_suspicious
[2025-04-23T10:23:48.630+0000] {task_command.py:410} INFO - Running <TaskInstance: transform.detect_suspicious manual__2025-04-23T10:21:37.571973+00:00 [running]> on host 9695aa16dd97
[2025-04-23T10:23:48.778+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='finbest' AIRFLOW_CTX_DAG_ID='transform' AIRFLOW_CTX_TASK_ID='detect_suspicious' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T10:21:37.571973+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-23T10:21:37.571973+00:00'
[2025-04-23T10:23:48.786+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2025-04-23T10:23:48.787+0000] {spark_submit.py:339} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --executor-cores 2 --executor-memory 2g --driver-memory 1g --name arrow-spark /opt/spark/detect_suspicious.py --jdbc jdbc:postgresql://postgres:5432/finbest --clickhouse-url jdbc:clickhouse://clickhouse:8123/finbest
[2025-04-23T10:23:48.869+0000] {spark_submit.py:490} INFO - /home/airflow/.local/lib/python3.7/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-04-23T10:23:48.869+0000] {spark_submit.py:490} INFO - JAVA_HOME is not set
[2025-04-23T10:23:48.880+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --executor-cores 2 --executor-memory 2g --driver-memory 1g --name arrow-spark /opt/spark/detect_suspicious.py --jdbc jdbc:postgresql://postgres:5432/finbest --clickhouse-url jdbc:clickhouse://clickhouse:8123/finbest. Error code is: 1.
[2025-04-23T10:23:48.882+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=transform, task_id=detect_suspicious, execution_date=20250423T102137, start_date=20250423T102348, end_date=20250423T102348
[2025-04-23T10:23:48.892+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 16 for task detect_suspicious (Cannot execute: spark-submit --master spark://spark-master:7077 --executor-cores 2 --executor-memory 2g --driver-memory 1g --name arrow-spark /opt/spark/detect_suspicious.py --jdbc jdbc:postgresql://postgres:5432/finbest --clickhouse-url jdbc:clickhouse://clickhouse:8123/finbest. Error code is: 1.; 866)
[2025-04-23T10:23:48.911+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-04-23T10:23:48.941+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
