[2025-05-09T21:48:32.445+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: superset_sync.create_graph_dashboard manual__2025-05-09T21:48:21.336883+00:00 [queued]>
[2025-05-09T21:48:32.451+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: superset_sync.create_graph_dashboard manual__2025-05-09T21:48:21.336883+00:00 [queued]>
[2025-05-09T21:48:32.451+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-05-09T21:48:32.460+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): create_graph_dashboard> on 2025-05-09 21:48:21.336883+00:00
[2025-05-09T21:48:32.464+0000] {standard_task_runner.py:57} INFO - Started process 23917 to run task
[2025-05-09T21:48:32.466+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'superset_sync', 'create_graph_dashboard', 'manual__2025-05-09T21:48:21.336883+00:00', '--job-id', '416', '--raw', '--subdir', 'DAGS_FOLDER/superset_sync.py', '--cfg-path', '/tmp/tmpdhy4le1b']
[2025-05-09T21:48:32.466+0000] {standard_task_runner.py:85} INFO - Job 416: Subtask create_graph_dashboard
[2025-05-09T21:48:32.478+0000] {logging_mixin.py:150} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-09T21:48:32.503+0000] {task_command.py:410} INFO - Running <TaskInstance: superset_sync.create_graph_dashboard manual__2025-05-09T21:48:21.336883+00:00 [running]> on host d3632ec65b22
[2025-05-09T21:48:32.565+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='superset_sync' AIRFLOW_CTX_TASK_ID='create_graph_dashboard' AIRFLOW_CTX_EXECUTION_DATE='2025-05-09T21:48:21.336883+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-09T21:48:21.336883+00:00'
[2025-05-09T21:48:32.885+0000] {superset_sync.py:83} INFO - Dataset уже есть (id=2)
[2025-05-09T21:48:33.075+0000] {superset_sync.py:247} INFO - ✔ создан чарт 'Размеры сообществ'
[2025-05-09T21:48:33.151+0000] {superset_sync.py:247} INFO - ✔ создан чарт 'Распределение степеней узлов'
[2025-05-09T21:48:33.193+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-05-09T21:48:33.201+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=superset_sync, task_id=create_graph_dashboard, execution_date=20250509T214821, start_date=20250509T214832, end_date=20250509T214833
[2025-05-09T21:48:33.240+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-05-09T21:48:33.259+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
